### ISSUE TITLE
Build copies theme files into subfolder, breaking theming

### ISSUE THREAD

**Issue by wjk** [gix/PresentationTheme.Aero#6]
Suddenly, and for no apparent reason (it started happening while I was tracking down an unrelated bug in my project), MSBuild is copying the theme assemblies into the `runtime\win\lib\netcoreapp3.0` subfolder. It did not do this before. As a result, the main assembly cannot find them and my app runs with the ugly default WPF theme. Please understand that this is an urgent issue for me, as I need to get the fix for that bug I mentioned above out as soon as possible, but this theme problem prevents me from doing a full release build, as then the theming won't work in the new version like it did in the old. Thanks!

#### `dotnet --info`

```
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.2.20479.15
 Commit:    da7dfa8840

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.20236
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\

Host (useful for support):
  Version: 5.0.0-rc.2.20475.5
  Commit:  c5a3f49c88

.NET SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by gix** [comment]
> MSBuild is copying the theme assemblies into the `runtime\win\lib\netcoreapp3.0` subfolder. It did not do this before.

Before meaning? What changed?

It is expected behavior for .NET Core that the specific runtime-loaded theme assemblies are copied to the `runtime\win` subfolder. This subfolder is also used when you publish the project using the `Portable` target runtime. If you publish using `win-x64` you get a flat file list.

I've just tried a new sample project in Visual Studio 2019 16.8 Preview 5.0 using `netcoreapp3.0` and `netcoreapp3.1` target frameworks, publishing as portable and win-x64 and all combinations worked fine.

Do you publish? What paths are in the `.deps.json` file?

**Comment by wjk** [comment]
During troubleshooting I copied the theme assemblies into the folder with the EXE, then ran the program; the theming then worked as expected. This is why I thought something had changed.

I am using a wapproj to build and ship my app using MSIX. I am using win-x64, but _not_ portable deployment. (The project is built FDD, then the framework assemblies are copied into the MSIX package during the build process.) I am not explicitly publishing my project, but this may or may not happen when the wapproj is built. Unfortunately, I cannot check my deps.json file at the moment as my Windows 10 computer is currently in the middle of a build upgrade. I'll get back to you as soon as possible. Thanks!

**Comment by wjk** [comment]
It turns out to have been a bug in my deployment process; the `*.deps.json` file was not being copied into the built package layout at all.
